name: Run automated tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install the dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: bundled-app
        path: dist

    - name: Run the server
      run: npx http-server dist &

    - name: Install Playwright Browsers
      run: npx playwright install firefox --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

